export { connect } from './actions/websocket'
export { request } from './actions/http'
export { auth } from './actions/auth'
export { LeagueWebSocket } from './modules/LeagueWebSocket'
export { Credentials, Effect, EventResponse, Dictionary, Request } from './schema'